default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: <%= ENV['LOCAL'] == 'docker' ? 'db' : 'localhost' %>
  port: 5432

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

test:
  <<: *default
  database: tech_interview_test<%= ENV['TEST_ENV_NUMBER'] %>